apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: decp
type: Opaque
stringData:
  # User Service
  USER_DB_URL: "jdbc:postgresql://ep-soft-rice-a1gwv5on-pooler.ap-southeast-1.aws.neon.tech/user_db?user=neondb_owner&password=npg_k5FMLjSVeEv9&sslmode=require&channelBinding=require"
  USER_DB_USERNAME: "neondb_owner"
  USER_DB_PASSWORD: "npg_k5FMLjSVeEv9"

  # Post Service
  POST_DB_URL: "jdbc:postgresql://ep-soft-rice-a1gwv5on-pooler.ap-southeast-1.aws.neon.tech/post_db?user=neondb_owner&password=npg_k5FMLjSVeEv9&sslmode=require&channelBinding=require"
  POST_DB_USERNAME: "neondb_owner"
  POST_DB_PASSWORD: "npg_k5FMLjSVeEv9"

  # Job Service
  JOB_DB_URL: "jdbc:postgresql://ep-soft-rice-a1gwv5on-pooler.ap-southeast-1.aws.neon.tech/job_db?user=neondb_owner&password=npg_k5FMLjSVeEv9&sslmode=require&channelBinding=require"
  JOB_DB_USERNAME: "neondb_owner"
  JOB_DB_PASSWORD: "npg_k5FMLjSVeEv9"

  # Event Service
  EVENT_DB_URL: "jdbc:postgresql://ep-soft-rice-a1gwv5on-pooler.ap-southeast-1.aws.neon.tech/event_db?user=neondb_owner&password=npg_k5FMLjSVeEv9&sslmode=require&channelBinding=require"
  EVENT_DB_USERNAME: "neondb_owner"
  EVENT_DB_PASSWORD: "npg_k5FMLjSVeEv9"

  # RabbitMQ
  SPRING_RABBITMQ_USERNAME: "guest"
  SPRING_RABBITMQ_PASSWORD: "guest"
