apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-service
  namespace: decp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-service
  template:
    metadata:
      labels:
        app: job-service
    spec:
      containers:
        - name: job-service
          image: asia-south1-docker.pkg.dev/decp-project/decp-repo/decp-job-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 15
